<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-10-27T12:18:05+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'timezone' => 'America/Asuncion',
);
