<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-06-27T13:53:11-04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'locale' => 'es_PY',
    'site' => 'Template Senatics',
    'version_installed' => '5.7.5.7',
    'misc' => array(
        'access_entity_updated' => 1464093190,
        'latest_version' => '5.7.5.8',
        'do_page_reindex_check' => false,
        'favicon_fid' => '38',
    ),
    'accessibility' => array(
        'toolbar_titles' => true,
        'toolbar_large_font' => false,
        'display_help_system' => true,
    ),
    'permissions' => array(
        'model' => 'advanced',
    ),
    'upload' => array(
        'extensions' => '*.flv;*.jpg;*.gif;*.jpeg;*.ico;*.docx;*.xla;*.png;*.psd;*.swf;*.doc;*.txt;*.xls;*.xlsx;*.csv;*.pdf;*.tiff;*.rtf;*.m4a;*.mov;*.wmv;*.mpeg;*.mpg;*.wav;*.3gp;*.avi;*.m4v;*.mp4;*.mp3;*.qt;*.ppt;*.pptx;*.kml;*.xml;*.svg;*.webm;*.ogg;*.ogv;*.css;*.js;*.zip;*.rar;*.ods;*.odt;*.woff;*.ttf;*.eot',
    ),
    'i18n' => array(
        'choose_language_login' => null,
    ),
);
