<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-05-18T13:46:34-04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Template SENATICs',
    'version_installed' => '5.7.5.13',
    'locale' => 'es_PY',
    'misc' => array(
        'access_entity_updated' => 1526487072,
        'do_page_reindex_check' => false,
    ),
    'accessibility' => array(
        'toolbar_titles' => true,
        'toolbar_large_font' => false,
        'display_help_system' => true,
    ),
    'i18n' => array(
        'choose_language_login' => null,
    ),
);
