<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-10-27T09:45:41-03:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'SENATICS Desarrollo',
    'version_installed' => '5.7.5.2',
    'locale' => 'es_PY',
    'misc' => array(
        'access_entity_updated' => 1443019881,
        'latest_version' => '5.7.5.1',
        'do_page_reindex_check' => false,
        'favicon_fid' => '15',
        'user_timezones' => false,
    ),
    'i18n' => array(
        'choose_language_login' => null,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'permissions' => array(
        'model' => 'advanced',
    ),
    'editor' => array(
        'concrete' => array(
            'enable_filemanager' => '1',
            'enable_sitemap' => '1',
        ),
        'plugins' => array(
            'selected' => array(
                'undoredo',
                'underline',
                'concrete5lightbox',
                'specialcharacters',
                'table',
                'fontfamily',
                'fontsize',
                'fontcolor',
            ),
        ),
    ),
    'security' => array(
        'ban' => array(
            'ip' => array(
                'enabled' => 0,
                'attempts' => '5',
                'time' => '300',
                'length' => '5',
            ),
        ),
    ),
    'accessibility' => array(
        'toolbar_titles' => true,
        'toolbar_large_font' => false,
        'display_help_system' => true,
    ),
);
