<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-02-19T10:56:26+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      banned_words
 * @group     conversations
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'banned_words' => true,
);
